package com.sdl.seatms.project.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-07-30T16:37:19.840+08:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "DeptPersonTransferService",
                  wsdlLocation = "http://hr.shidanli.cn/services/DeptPersonTransferService?wsdl",
                  targetNamespace = "http://transfer.server.webServices.hr.com")
public class DeptPersonTransferService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://transfer.server.webServices.hr.com", "DeptPersonTransferService");
    public final static QName DeptPersonTransferServiceHttpSoap11Endpoint = new QName("http://transfer.server.webServices.hr.com", "DeptPersonTransferServiceHttpSoap11Endpoint");
    public final static QName DeptPersonTransferServiceHttpEndpoint = new QName("http://transfer.server.webServices.hr.com", "DeptPersonTransferServiceHttpEndpoint");
    public final static QName DeptPersonTransferServiceHttpSoap12Endpoint = new QName("http://transfer.server.webServices.hr.com", "DeptPersonTransferServiceHttpSoap12Endpoint");
    static {
        URL url = null;
        try {
            url = new URL("http://hr.shidanli.cn/services/DeptPersonTransferService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DeptPersonTransferService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://hr.shidanli.cn/services/DeptPersonTransferService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DeptPersonTransferService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DeptPersonTransferService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeptPersonTransferService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DeptPersonTransferService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DeptPersonTransferService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DeptPersonTransferService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DeptPersonTransferServicePortType
     */
    @WebEndpoint(name = "DeptPersonTransferServiceHttpSoap11Endpoint")
    public DeptPersonTransferServicePortType getDeptPersonTransferServiceHttpSoap11Endpoint() {
        return super.getPort(DeptPersonTransferServiceHttpSoap11Endpoint, DeptPersonTransferServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeptPersonTransferServicePortType
     */
    @WebEndpoint(name = "DeptPersonTransferServiceHttpSoap11Endpoint")
    public DeptPersonTransferServicePortType getDeptPersonTransferServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(DeptPersonTransferServiceHttpSoap11Endpoint, DeptPersonTransferServicePortType.class, features);
    }


    /**
     *
     * @return
     *     returns DeptPersonTransferServicePortType
     */
    @WebEndpoint(name = "DeptPersonTransferServiceHttpEndpoint")
    public DeptPersonTransferServicePortType getDeptPersonTransferServiceHttpEndpoint() {
        return super.getPort(DeptPersonTransferServiceHttpEndpoint, DeptPersonTransferServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeptPersonTransferServicePortType
     */
    @WebEndpoint(name = "DeptPersonTransferServiceHttpEndpoint")
    public DeptPersonTransferServicePortType getDeptPersonTransferServiceHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(DeptPersonTransferServiceHttpEndpoint, DeptPersonTransferServicePortType.class, features);
    }


    /**
     *
     * @return
     *     returns DeptPersonTransferServicePortType
     */
    @WebEndpoint(name = "DeptPersonTransferServiceHttpSoap12Endpoint")
    public DeptPersonTransferServicePortType getDeptPersonTransferServiceHttpSoap12Endpoint() {
        return super.getPort(DeptPersonTransferServiceHttpSoap12Endpoint, DeptPersonTransferServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeptPersonTransferServicePortType
     */
    @WebEndpoint(name = "DeptPersonTransferServiceHttpSoap12Endpoint")
    public DeptPersonTransferServicePortType getDeptPersonTransferServiceHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(DeptPersonTransferServiceHttpSoap12Endpoint, DeptPersonTransferServicePortType.class, features);
    }

}
