
package com.sdl.seatms.project.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-07-30T16:37:19.789+08:00
 * Generated source version: 3.3.2
 *
 */
public final class DeptPersonTransferServicePortType_DeptPersonTransferServiceHttpSoap12Endpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://transfer.server.webServices.hr.com", "DeptPersonTransferService");

    private DeptPersonTransferServicePortType_DeptPersonTransferServiceHttpSoap12Endpoint_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DeptPersonTransferService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        DeptPersonTransferService ss = new DeptPersonTransferService(wsdlURL, SERVICE_NAME);
        DeptPersonTransferServicePortType port = ss.getDeptPersonTransferServiceHttpSoap12Endpoint();

        {
        System.out.println("Invoking getDeptList...");
        java.lang.String _getDeptList__return = port.getDeptList();
        System.out.println("getDeptList.result=" + _getDeptList__return);


        }
        {
        System.out.println("Invoking getParaList...");
        java.lang.String _getParaList_paraTypeCode = "";
        java.lang.String _getParaList__return = port.getParaList(_getParaList_paraTypeCode);
        System.out.println("getParaList.result=" + _getParaList__return);


        }
        {
        System.out.println("Invoking getPersonList...");
        java.lang.String _getPersonList_date = "";
        java.lang.String _getPersonList__return = port.getPersonList(_getPersonList_date);
        System.out.println("getPersonList.result=" + _getPersonList__return);


        }

        System.exit(0);
    }

}
